{% set name = "snakemake-toyworkflow" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: generic
  script: |
    mkdir -p $PREFIX/share/snakemake-toyworkflow
    cp Snakefile script.py config.yaml $PREFIX/share/snakemake-toyworkflow/
    if [ -d "envs" ]; then cp -r envs $PREFIX/share/snakemake-toyworkflow/; fi
    mkdir -p $PREFIX/bin
    cat << 'EOF' > $PREFIX/bin/run-toyworkflow
    #!/bin/bash
    set -e
    
    # Show help if requested
    if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "help" ]]; then
        cat << 'HELP'
    Snakemake Toy Workflow - A simple data processing workflow
    
    USAGE:
        run-toyworkflow [snakemake-options]
    
    EXAMPLES:
        run-toyworkflow --cores 1                    # Run with 1 core
        run-toyworkflow --cores 4 --dry-run         # Dry run with 4 cores
        run-toyworkflow --dag                       # Show workflow DAG
        run-toyworkflow --report report.html        # Generate HTML report
    
    WORKFLOW:
        - Reads data from: data/input.txt (CSV format)
        - Processes data and generates statistics
        - Creates plots in: results/plot.pdf
        - Outputs results to: results/output.txt
    
    REQUIREMENTS:
        - Input file: data/input.txt (CSV with 'time' and 'value' columns)
        - Creates: results/ directory for outputs
    
    For more Snakemake options, see: snakemake --help
    HELP
        exit 0
    fi
    
    # Get the workflow directory
    WORKFLOW_DIR="$CONDA_PREFIX/share/snakemake-toyworkflow"
    
    # Check if workflow directory exists
    if [ ! -d "$WORKFLOW_DIR" ]; then
        echo "Error: Workflow directory not found: $WORKFLOW_DIR"
        exit 1
    fi
    
    # Change to workflow directory and run snakemake
    cd "$WORKFLOW_DIR"
    exec snakemake "$@"
    EOF
    chmod +x $PREFIX/bin/run-toyworkflow

requirements:
  run:
    - python >=3.9
    - snakemake
    - pandas
    - matplotlib
    - pyyaml

test:
  commands:
    - run-toyworkflow --help
    - test -f $PREFIX/share/snakemake-toyworkflow/Snakefile
    - test -f $PREFIX/share/snakemake-toyworkflow/script.py
    - test -f $PREFIX/share/snakemake-toyworkflow/config.yaml

about:
  summary: A simple, portable Snakemake workflow package for CSV data processing and plotting
  description: |
    A generic Snakemake workflow that processes CSV data and generates statistical 
    analysis and visualizations. The workflow reads input data from data/input.txt 
    and produces results in the results/ directory.
  license: MIT 